### ISSUE TITLE
Multiple services

### ISSUE THREAD

**Issue by KidkArolis** [mcollina/upring#1]
I appreciate this library is pretty fresh. But is it in the plans to add support for multiple service types? I.e. when requesting, I should be able to specify which service I want to handle the request. I think that's what you're able to do in hyperbahn. Or is upring meant to be a lower level thing (like ringpop), and the service concept would have to be implemented in a different lib?

**Comment by mcollina** [comment]
This is in my roadmap, but you can use http://npm.im/object-router for the time being.

**Comment by KidkArolis** [comment]
I don't see how object-router helps as it seems to only work within one instance. As in, I want my upring to consist of S1-S2-S1-S3-S4-S5-S1-S2-S1

Where each S1, S2, S3... is a different repo, a different service.

Or are you suggesting that if a node doesn't know how to handle a specific command, it just requests itself into the ring, until someone can answer?

Basically, yeah, I guess I'm talking about some kind of routing layer on top of upring where not only do I want to be able to make a request to a node, I want to also know what types of nodes are out there.

**Comment by mcollina** [comment]
Sorry, I understood you wanted to run multiple types of "requests" on every node, different "commands": object-router helps with that.
upring does not provides the routing/discovery layer of services, it just do the sharding bit (with transports). It will also include the logic for circuit breaking when forwarding requests (I'm working on this right now).
