### ISSUE TITLE
Base node - single point of failure

### ISSUE THREAD

**Issue by KidkArolis** [mcollina/upring#2]
I was wondering how is this meant to work in practise. Basically, we're talking about this distributed ring of nodes here, but we still have a single point of failure - the base node. If that goes down - no new nodes can connect to the ring. So, how would you make the base node resilient in production in practise?

**Comment by KidkArolis** [comment]
Is the idea simply that keeping one (load balanced for redundancy) base node is a much more managable task than keeping traditonal config/sharding/load balancing/app services up.

Sorry if this isn't making much sense, just trying to wrap my head around it. The concept of doing application level sharding and config propagation sounds fascinating.

**Comment by mcollina** [comment]
@KidkArolis the base node can be any peer. It has nothing special, and it is just used by the current peer to boostrap. With [baseswim](https://github.com/mcollina/baseswim) you can even tell another peer to join the new peer. I need to document all this :D, would you like to help?

**Comment by KidkArolis** [comment]
I get that, but the problem is that at the time a new node is being added to the ring it needs to know the address of some other node. You could do some kind of network broadcast, but I hear that doesn't work very well. So the only way I can see this could be done is by maintaining a small number of based nodes that are permanently bound to some known address and making sure they're always up.

**Comment by mcollina** [comment]
Sorry for the long wait. I just saw this left open.

A trick is to fetch it from your cloud instance description. Your code can use your cloud API to retrieve information about all running instances region/availability zone in AWS term. You just need a little cluster of those.

If you use docker swarm or kubernetes, you can use the monitoring HTTP endpoint from https://github.com/mcollina/baseswim to discover some peers.
